"""Assemble the demo SVGs into a single self-contained HTML gallery."""

from pathlib import Path

from _common import output_dir

# (filename prefix, section title) in display order.
CATEGORIES = [
    ("layout_", "Layouts"),
    ("styling_", "Styling"),
    ("algo_", "Algorithms"),
    ("generator_", "Generators"),
    ("io_", "I/O"),
]

PAGE_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem;
  font: 15px/1.5 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
  background: #fbfbfd; color: #1d1d1f;
}
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
.sub { color: #6e6e73; margin: 0 0 2rem; }
h2 {
  font-size: 1.15rem; margin: 2.5rem 0 1rem;
  padding-bottom: .4rem; border-bottom: 1px solid #e1e1e6;
}
.grid {
  display: grid; gap: 1.25rem;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
}
figure {
  margin: 0; padding: .75rem;
  background: #fff; border: 1px solid #e1e1e6; border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0,0,0,.04);
}
.frame {
  display: flex; align-items: center; justify-content: center;
  height: 220px; overflow: hidden;
}
.frame svg { max-width: 100%; max-height: 100%; height: auto; width: auto; }
figcaption {
  margin-top: .6rem; font-size: .85rem; color: #6e6e73; text-align: center;
}
@media (prefers-color-scheme: dark) {
  body { background: #1c1c1e; color: #f5f5f7; }
  .sub, figcaption { color: #98989d; }
  h2 { border-color: #3a3a3c; }
  figure { background: #2c2c2e; border-color: #3a3a3c; }
}
"""


def _inline_svg(path: Path) -> str:
    """Return just the <svg>...</svg> element (drop the XML prolog)."""
    text = path.read_text()
    start = text.find("<svg")
    return text[start:] if start != -1 else text


def _title(path: Path, prefix: str) -> str:
    name = path.stem[len(prefix):] if path.stem.startswith(prefix) else path.stem
    return name.replace("_", " ")


def build(out: Path) -> Path:
    svgs = sorted(out.glob("*.svg"))
    used: set[Path] = set()

    sections = []
    for prefix, title in CATEGORIES:
        items = [p for p in svgs if p.name.startswith(prefix)]
        used.update(items)
        if not items:
            continue
        cards = "\n".join(
            f'<figure><div class="frame">{_inline_svg(p)}</div>'
            f"<figcaption>{_title(p, prefix)}</figcaption></figure>"
            for p in items
        )
        sections.append(f"<h2>{title}</h2>\n<div class='grid'>{cards}</div>")

    leftovers = [p for p in svgs if p not in used]
    if leftovers:
        cards = "\n".join(
            f'<figure><div class="frame">{_inline_svg(p)}</div>'
            f"<figcaption>{p.stem.replace('_', ' ')}</figcaption></figure>"
            for p in leftovers
        )
        sections.append(f"<h2>Other</h2>\n<div class='grid'>{cards}</div>")

    html = (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>ogdf-py demo gallery</title>"
        f"<style>{PAGE_CSS}</style></head><body>"
        "<h1>ogdf-py demo gallery</h1>"
        f"<p class='sub'>{len(svgs)} drawings generated by the demos.</p>"
        + "\n".join(sections)
        + "</body></html>"
    )

    path = out / "index.html"
    path.write_text(html)
    return path


def main():
    out = output_dir()
    path = build(out)
    print("Gallery:")
    print(f"  {sum(1 for _ in out.glob('*.svg'))} drawings -> {path.name}")


if __name__ == "__main__":
    main()
