"""Assemble the demo SVGs into galleries.

Produces two outputs:
  * a standalone self-contained ``build/demo-output/index.html``
  * ``docs/gallery.md``, a page for the MkDocs documentation site
"""

from pathlib import Path

from _common import output_dir

ROOT = Path(__file__).resolve().parent.parent

# (filename prefix, section title) in display order.
CATEGORIES = [
    ("layout_", "Layouts"),
    ("styling_", "Styling"),
    ("algo_", "Algorithms"),
    ("generator_", "Generators"),
    ("io_", "I/O"),
]

# Grid styling for the MkDocs page (uses Material's CSS variables so it adapts
# to the light/dark theme). Drawings sit on a white card so the black strokes
# stay visible in dark mode.
MD_CSS = """<style>
/* Let the gallery page use the full window width (this <style> only loads on
   the gallery page, so it does not affect the rest of the site). */
.md-grid { max-width: initial; }
.ogdf-gallery {
  display: grid; gap: 1.25rem; margin: 1rem 0;
  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
}
.ogdf-gallery figure {
  margin: 0; padding: .75rem; border-radius: .5rem;
  border: 1px solid var(--md-default-fg-color--lightest); background: #fff;
}
.ogdf-gallery .frame {
  display: flex; align-items: center; justify-content: center;
  height: 300px; overflow: hidden;
}
/* OGDF SVGs carry only a viewBox (no width/height); fill the frame explicitly
   so they scale up. The viewBox + default preserveAspectRatio keeps them
   undistorted and centered. The double-class selector beats Material's own
   `.md-typeset svg` rule. */
.ogdf-gallery .frame svg { width: 100%; height: 100%; }
.ogdf-gallery figcaption {
  margin-top: .6rem; text-align: center; font-size: .85rem;
  color: var(--md-default-fg-color--light);
}
</style>"""

PAGE_CSS = """
:root { color-scheme: light dark; }
* { box-sizing: border-box; }
body {
  margin: 0; padding: 2rem;
  font: 15px/1.5 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
  background: #fbfbfd; color: #1d1d1f;
}
h1 { font-size: 1.6rem; margin: 0 0 .25rem; }
.sub { color: #6e6e73; margin: 0 0 2rem; }
h2 {
  font-size: 1.15rem; margin: 2.5rem 0 1rem;
  padding-bottom: .4rem; border-bottom: 1px solid #e1e1e6;
}
.grid {
  display: grid; gap: 1.25rem;
  grid-template-columns: repeat(auto-fill, minmax(260px, 1fr));
}
figure {
  margin: 0; padding: .75rem;
  background: #fff; border: 1px solid #e1e1e6; border-radius: 10px;
  box-shadow: 0 1px 3px rgba(0,0,0,.04);
}
.frame {
  display: flex; align-items: center; justify-content: center;
  height: 220px; overflow: hidden;
}
.frame svg { max-width: 100%; max-height: 100%; height: auto; width: auto; }
figcaption {
  margin-top: .6rem; font-size: .85rem; color: #6e6e73; text-align: center;
}
@media (prefers-color-scheme: dark) {
  body { background: #1c1c1e; color: #f5f5f7; }
  .sub, figcaption { color: #98989d; }
  h2 { border-color: #3a3a3c; }
  figure { background: #2c2c2e; border-color: #3a3a3c; }
}
"""


def _inline_svg(path: Path) -> str:
    """Return just the <svg>...</svg> element (drop the XML prolog)."""
    text = path.read_text()
    start = text.find("<svg")
    return text[start:] if start != -1 else text


def _title(path: Path, prefix: str) -> str:
    name = path.stem[len(prefix):] if path.stem.startswith(prefix) else path.stem
    return name.replace("_", " ")


def _inline_svg_flat(path: Path) -> str:
    """Inlined SVG with blank lines removed (a blank line would end the raw
    HTML block in Markdown and break the surrounding grid)."""
    svg = _inline_svg(path)
    return "\n".join(line for line in svg.splitlines() if line.strip())


def build(out: Path) -> Path:
    svgs = sorted(out.glob("*.svg"))
    used: set[Path] = set()

    sections = []
    for prefix, title in CATEGORIES:
        items = [p for p in svgs if p.name.startswith(prefix)]
        used.update(items)
        if not items:
            continue
        cards = "\n".join(
            f'<figure><div class="frame">{_inline_svg(p)}</div>'
            f"<figcaption>{_title(p, prefix)}</figcaption></figure>"
            for p in items
        )
        sections.append(f"<h2>{title}</h2>\n<div class='grid'>{cards}</div>")

    leftovers = [p for p in svgs if p not in used]
    if leftovers:
        cards = "\n".join(
            f'<figure><div class="frame">{_inline_svg(p)}</div>'
            f"<figcaption>{p.stem.replace('_', ' ')}</figcaption></figure>"
            for p in leftovers
        )
        sections.append(f"<h2>Other</h2>\n<div class='grid'>{cards}</div>")

    html = (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        "<title>ogdf-py demo gallery</title>"
        f"<style>{PAGE_CSS}</style></head><body>"
        "<h1>ogdf-py demo gallery</h1>"
        f"<p class='sub'>{len(svgs)} drawings generated by the demos.</p>"
        + "\n".join(sections)
        + "</body></html>"
    )

    path = out / "index.html"
    path.write_text(html)
    return path


def build_docs_page(out: Path) -> Path:
    """Write docs/gallery.md for the MkDocs site (SVGs inlined)."""
    svgs = sorted(out.glob("*.svg"))
    used: set[Path] = set()

    parts = [
        "# Gallery",
        "",
        MD_CSS,
        "",
        f"{len(svgs)} drawings generated by the demos. Regenerate with "
        "`make demos`.",
        "",
    ]

    def add_section(title: str, items: list[Path], prefix: str) -> None:
        cards = [
            f'<figure><div class="frame">{_inline_svg_flat(p)}</div>'
            f"<figcaption>{_title(p, prefix)}</figcaption></figure>"
            for p in items
        ]
        parts.append(f"## {title}")
        parts.append("")
        parts.append('<div class="ogdf-gallery">')
        parts.extend(cards)  # no blank lines inside the raw HTML block
        parts.append("</div>")
        parts.append("")

    for prefix, title in CATEGORIES:
        items = [p for p in svgs if p.name.startswith(prefix)]
        used.update(items)
        if items:
            add_section(title, items, prefix)

    leftovers = [p for p in svgs if p not in used]
    if leftovers:
        add_section("Other", leftovers, "")

    page = ROOT / "docs" / "gallery.md"
    page.write_text("\n".join(parts) + "\n")
    return page


def main():
    out = output_dir()
    html = build(out)
    docs_page = build_docs_page(out)
    n = sum(1 for _ in out.glob("*.svg"))
    print("Gallery:")
    print(f"  {n} drawings -> {html.name}")
    print(f"  {n} drawings -> docs/{docs_page.name}")


if __name__ == "__main__":
    main()
